import{useEffect,useRef,useState}from'react';
import{Plus,Search,ArrowUp,Square,Paperclip,FolderOpen,ChevronDown,Copy,Sparkles,RefreshCw,Check,Trash2,MoreHorizontal,X,Menu}from'lucide-react';
import ReactMarkdown from'react-markdown';import remarkGfm from'remark-gfm';import rehypeHighlight from'rehype-highlight';
import{remote,Dict,routeHeaders,streamEvents,download}from'./api';import{mergeEvent,Message}from'./events';
import{displayParts}from'./thinking';

function Reasoning({text}:{text:string}){
 const firstLine=text.trim().split(/\r?\n/,1)[0];
 return <details className="tool reasoning"><summary><span className="reasoning-label">思考过程</span><span className="reasoning-preview">{firstLine||'正在思考…'}</span></summary><div className="reasoning-content"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeHighlight]}>{text}</ReactMarkdown></div></details>;
}

export function Chat({onConnect}:{onConnect:()=>void}){
 const[agents,setAgents]=useState<Dict[]>([]),[agent,setAgent]=useState(localStorage.getItem('agent')||'agent-code'),[user,setUser]=useState(localStorage.getItem('username')||'local-demo');
 const[showSidebar,setShowSidebar]=useState(false);
 const[models,setModels]=useState<Dict[]>([]),[model,setModel]=useState(''),[sessions,setSessions]=useState<Dict[]>([]),[session,setSession]=useState(''),[search,setSearch]=useState('');
 const[messages,setMessages]=useState<Message[]>([]),[prompt,setPrompt]=useState(''),[busy,setBusy]=useState(false),[submitting,setSubmitting]=useState(false),[connected,setConnected]=useState(false),[error,setError]=useState('');
 const[attachments,setAttachments]=useState<Dict[]>([]),[pending,setPending]=useState<Dict[]>([]),[files,setFiles]=useState<Dict[]|null>(null),[filePath,setFilePath]=useState('.');
 const [filesLoading,setFilesLoading]=useState(false);
 const fileView=useRef<{path:string}|null>(null),fileRequest=useRef(0);
 const sessionRef=useRef(session),bottom=useRef<HTMLDivElement>(null),picker=useRef<HTMLInputElement>(null),ownerRef=useRef(''),eventRevision=useRef(0);
 const owner=agent+':'+user;ownerRef.current=owner;
 const active=agents.find(a=>a.id===agent),headers=routeHeaders(agent,user);
 const reloadSessions=()=>remote('/session','GET',undefined,headers).then(rows=>{if(ownerRef.current===owner)setSessions(rows)});
 const loadHistory=async(id:string)=>{const revision=eventRevision.current;const result:Message[]=await remote(`/session/${id}/message`,'GET',undefined,headers);if(sessionRef.current!==id||ownerRef.current!==owner)return;setMessages(current=>{if(revision===eventRevision.current)return result;const merged=new Map(result.map(m=>[m.info.id,m]));for(const m of current){const old=merged.get(m.info.id);merged.set(m.info.id,old?{info:{...old.info,...m.info},parts:[...new Map([...old.parts,...m.parts].map(p=>[p.id,p])).values()]}:m)}return [...merged.values()]});};
 const select=async(id:string)=>{setShowSidebar(false);fileView.current=null;fileRequest.current++;setFiles(null);setFilesLoading(false);localStorage.setItem('session:'+owner,id);sessionRef.current=id;setSession(id);setMessages([]);setAttachments([]);setPending([]);setError('');setBusy(false);if(id){try{await loadHistory(id);const statuses=await remote('/session/status','GET',undefined,headers);if(sessionRef.current===id&&ownerRef.current===owner)setBusy(['busy','retry'].includes(statuses[id]?.type));}catch(e:any){if(ownerRef.current===owner)setError(e.message)}}};
 useEffect(()=>{remote('/cloud/agents').then(setAgents).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!active)return;localStorage.setItem('agent',agent);localStorage.setItem('username',user);select(localStorage.getItem('session:'+owner)||'');setConnected(false);setError('');setSessions([]);
 remote(`/cloud/models?agent_id=${encodeURIComponent(agent)}`).then(ms=>{if(ownerRef.current!==owner)return;setModels(ms);setModel(ms.find((m:Dict)=>m.id===active?.default_model_id)?.id||ms[0]?.id||'')}).catch(e=>setError(e.message));reloadSessions().catch(e=>setError(e.message));
 const abort=new AbortController();let timer:ReturnType<typeof setTimeout>;
 const refreshPending=()=>Promise.all(['/permission','/question'].map(async path=>{try{const r=await remote(path,'GET',undefined,{...headers,...(sessionRef.current?{'X-Cloud-Session-ID':sessionRef.current}:{})});return r.map((x:Dict)=>({...x,_kind:path.slice(1)}));}catch{return []}})).then(r=>{if(!abort.signal.aborted)setPending(r.flat())});
 const connect=async()=>{try{await streamEvents(headers,abort.signal,event=>{if(abort.signal.aborted||ownerRef.current!==owner)return;eventRevision.current++;if(event.type==='server.connected'){setConnected(true);setError('');refreshPending();refreshFiles();if(sessionRef.current){loadHistory(sessionRef.current).catch(()=>{});remote('/session/status','GET',undefined,headers).then(statuses=>{if(!abort.signal.aborted)setBusy(['busy','retry'].includes(statuses[sessionRef.current]?.type))}).catch(()=>{});}return;}
 const p=event.properties||{},sid=p.sessionID||p.info?.sessionID||p.part?.sessionID;
 if(sid===sessionRef.current){setMessages(old=>mergeEvent(old,event,sessionRef.current));if(event.type==='session.status'){setBusy(['busy','retry'].includes(p.status?.type));if(p.status?.type==='idle'){loadHistory(sid).catch(()=>{});refreshFiles();}}if(event.type==='session.idle'){setBusy(false);loadHistory(sid).catch(()=>{});refreshFiles();}if(event.type==='session.error')setError('远端执行失败，请查看消息详情或手动重试');}
 if(event.type.startsWith('permission.')||event.type.startsWith('question.'))refreshPending();if(event.type==='session.updated'||event.type==='session.created')reloadSessions().catch(()=>{});
 });}catch(e:any){if(!abort.signal.aborted){setConnected(false);setError('事件流断开，正在重连；不会重复提交消息');timer=setTimeout(connect,3000);}}};connect();
 return()=>{abort.abort();clearTimeout(timer)};
 },[agent,user,!!active]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages,busy]);
 useEffect(()=>{if(!session)return;let cancelled=false;Promise.all(['/permission','/question'].map(async path=>{
  const rows=await remote(path,'GET',undefined,{...headers,'X-Cloud-Session-ID':session});return rows.map((x:Dict)=>({...x,_kind:path.slice(1)}));
 })).then(rows=>{if(!cancelled&&sessionRef.current===session&&ownerRef.current===owner)setPending(rows.flat())}).catch(()=>{});return()=>{cancelled=true}},[session,owner]);
 async function ensureSession(){if(sessionRef.current)return sessionRef.current;const created=await remote('/session','POST',{_cloud:{agent_id:agent,username:user}},headers);if(ownerRef.current!==owner)throw Error('Agent 已切换，新会话已保留在原 Agent 历史中');sessionRef.current=created.id;setSession(created.id);localStorage.setItem('session:'+owner,created.id);await reloadSessions();return created.id;}
 async function send(){if(!prompt.trim()||busy||submitting||!connected||!model)return;setSubmitting(true);setError('');try{const id=await ensureSession();const text=prompt;const fileContext=attachments.length?'\n\n已上传到远端工作区的附件：\n'+attachments.map(a=>a.path).join('\n'):'';
 await remote(`/session/${id}/prompt_async`,'POST',{messageID:'msg_'+crypto.randomUUID().replaceAll('-',''),model:{providerID:'cloud-model-gateway',modelID:model},parts:[{type:'text',text:text+fileContext}]},headers);
 if(ownerRef.current===owner&&sessionRef.current===id){setPrompt('');setAttachments([]);setBusy(true);loadHistory(id).catch(()=>{});}
 }catch(e:any){setError(e.message+'。请求状态不确定时请先刷新历史，避免重复提交。')}finally{setSubmitting(false)}}
 async function upload(selected:FileList|null){if(!selected)return;try{const id=await ensureSession();for(const file of Array.from(selected)){const form=new FormData();form.set('file',file);form.set('agent_id',agent);form.set('username',user);form.set('session_id',id);form.set('relative_path','inputs/'+file.name);const result=await remote('/cloud/files/upload','POST',form);if(result.size!==file.size)throw Error('Upload size mismatch');refreshFiles();if(ownerRef.current===owner&&sessionRef.current===id)setAttachments(a=>[...a,{name:file.name,...result}]);}}catch(e:any){setError(e.message)}finally{if(picker.current)picker.current.value=''}}
 function refreshFiles(){if(fileView.current)void browse(fileView.current.path);}
 async function browse(path='.'){
  const id=sessionRef.current;if(!id)return;
  fileView.current={path};const version=++fileRequest.current;setFilesLoading(true);
  try{const query=new URLSearchParams({agent_id:agent,username:user,session_id:id,path});const result=await remote('/cloud/files/list?'+query);
   if(ownerRef.current===owner&&sessionRef.current===id&&version===fileRequest.current){setFiles(result.entries);setFilePath(path);}
  }catch(e:any){if(ownerRef.current===owner&&sessionRef.current===id&&version===fileRequest.current)setError(e.message)}
  finally{if(version===fileRequest.current)setFilesLoading(false)}
 }

 async function manageSession(s:Dict,action:string){try{if(action==='delete'){if(!confirm('删除该会话？此操作不会删除整个工作区。'))return;await remote('/session/'+s.id,'DELETE',undefined,headers);if(session===s.id)select('');}else{const title=window.prompt('会话名称',s.title);if(title===null)return;await remote('/session/'+s.id,'PATCH',{title},headers);}await reloadSessions();}catch(e:any){setError(e.message)}}
 async function answer(item:Dict,value:any){try{const path=item._kind==='question'?`/question/${item.id}/reply`:`/permission/${item.id}/reply`;await remote(path,'POST',item._kind==='question'?{answers:value}:{reply:value},{...headers,'X-Cloud-Session-ID':item.sessionID});setPending(p=>p.filter(x=>x.id!==item.id));}catch(e:any){setError(e.message)}}
 return <div className={"chat-layout "+(showSidebar?"sidebar-open":"")}><aside className="session-sidebar"><button className="new-chat" onClick={()=>select('')}><Plus size={18}/>新对话</button><label className="search"><Search size={15}/><input placeholder="搜索会话" value={search} onChange={e=>setSearch(e.target.value)}/></label><span className="eyebrow">你的对话</span><div className="session-list">{sessions.filter(s=>(s.title||s.id).toLowerCase().includes(search.toLowerCase())).map(s=><div className={'session-row '+(s.id===session?'active':'')} key={s.id}><button onClick={()=>select(s.id)}>{s.title||'未命名对话'}</button><button className="icon" title="重命名" onClick={()=>manageSession(s,'rename')}><MoreHorizontal size={15}/></button><button className="icon" title="删除" onClick={()=>manageSession(s,'delete')}><Trash2 size={14}/></button></div>)}</div><div className="sidebar-footer"><span className="eyebrow">会话命名空间</span><input aria-label="会话命名空间" value={user} onChange={e=>setUser(e.target.value.replace(/[^a-zA-Z0-9_-]/g,''))}/><p>会话和文件保存在服务器</p></div></aside>
 <section className="conversation"><div className="conversation-toolbar"><button className="icon mobile-menu" aria-label="会话列表" onClick={()=>setShowSidebar(!showSidebar)}><Menu size={18}/></button><select aria-label="选择 Agent" value={agent} onChange={e=>setAgent(e.target.value)}>{agents.map(a=><option key={a.id} value={a.id}>{a.name||a.id}{a.enabled?'':' · 已停用'}</option>)}</select><span className="version" title={(active?.bindings||[]).map((b:Dict)=>b.id+" · v"+b.version).join("\n")||"未绑定扩展"}>v{active?.version||'—'} · {active?.bindings?.length||0} 个扩展</span><span className={'stream-status '+(connected?'online':'')}>{connected?'流已连接':'连接中'}</span><button className="icon" title="查看产物" onClick={()=>browse()} disabled={!session}><FolderOpen size={19}/></button></div>
 {error&&<div className="notice error"><span>{error}</span><button onClick={onConnect}>连接设置</button><button className="icon" onClick={()=>setError('')}><X size={14}/></button></div>}
 <div className="message-scroll">{!session&&!messages.length?<div className="welcome"><span className="welcome-symbol"><Sparkles size={34}/></span><p className="eyebrow">YOUR CLOUD, YOUR AGENTS</p><h1>让想法，在云端发生。</h1><p>连接你的 Agent，从一个问题开始。</p><div className="suggestions">{['检查项目结构，帮我梳理下一步','分析一份数据，并生成报告','写一个脚本，解决重复工作'].map((s,i)=><button key={s} onClick={()=>setPrompt(s)}><span>0{i+1}</span>{s}<ArrowUp size={16}/></button>)}</div></div>:<div className="messages">{messages.map(m=><article key={m.info.id} className={'message '+m.info.role}>{m.info.role!=='user'&&<span className="message-symbol"><Sparkles size={18}/></span>}<div className="message-content">{displayParts(m.parts,m.info.role==='assistant',busy&&!m.info.time?.completed).map((p,i)=>p.type==='text'?<ReactMarkdown key={p.id||i} remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeHighlight]}>{p.text||''}</ReactMarkdown>:p.type==='tool'?<details className="tool" key={p.id||i}><summary>{p.state?.status==='completed'?<Check size={14}/>:<RefreshCw size={14}/>} {p.tool} <span>{p.state?.status}</span></summary><pre>{JSON.stringify(p.state?.input,null,2)}</pre><pre>{typeof p.state?.output==='string'?p.state.output:JSON.stringify(p.state?.output||p.state?.error,null,2)}</pre></details>:p.type==='reasoning'?<Reasoning key={p.id||i} text={p.text||''}/>:p.type==='file'?<p key={p.id||i}>附件：{p.filename||p.url}</p>:null)}{m.info.error&&<div className="notice error">{m.info.error.name||'执行失败'} · {m.info.error.data?.message}</div>}<button className="copy-message icon" title="复制回答" onClick={()=>navigator.clipboard.writeText(displayParts(m.parts,m.info.role==='assistant',busy&&!m.info.time?.completed).filter(p=>p.type==='text').map(p=>p.text).join('\n'))}><Copy size={14}/></button></div></article>)}{busy&&<div className="thinking"><span/><span/><span/> Agent 正在执行</div>}<div ref={bottom}/></div>}</div>
 <div className="composer-area">{!busy&&messages.some(m=>m.info.error)&&<button className="secondary" onClick={()=>{const previous=[...messages].reverse().find(m=>m.info.role==='user');if(previous)setPrompt(previous.parts.filter(p=>p.type==='text').map(p=>p.text).join('\n'));}}>重新编辑上一条并重试</button>}{pending.filter(p=>p.sessionID===session).map(p=><div className="approval" key={p.id}><strong>{p._kind==='permission'?'Agent 请求权限':'Agent 需要补充信息'}</strong><p>{p.permission||p.questions?.map((q:Dict)=>q.question).join('\n')}</p>{p._kind==='permission'?<div className="actions"><button onClick={()=>answer(p,'once')}>允许一次</button><button onClick={()=>answer(p,'always')}>始终允许</button><button onClick={()=>answer(p,'reject')}>拒绝</button></div>:<Question item={p} onAnswer={v=>answer(p,v)}/>}</div>)}
 <div className="composer">{attachments.length>0&&<div className="chips">{attachments.map((a,i)=><span key={i}>{a.name}<button onClick={()=>setAttachments(x=>x.filter((_,j)=>i!==j))}>×</button></span>)}</div>}<textarea aria-label="消息" placeholder="向 Agent 提问，或交给它一个任务…" value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><div className="composer-bottom"><input ref={picker} type="file" multiple hidden onChange={e=>upload(e.target.files)}/><button className="icon" title="上传附件" onClick={()=>picker.current?.click()}><Paperclip size={19}/></button><select aria-label="选择模型" value={model} onChange={e=>setModel(e.target.value)}>{models.map(m=><option key={m.id} value={m.id}>{m.name||m.id}</option>)}</select><span className="grow"/>{busy?<button className="send" title="停止生成" onClick={()=>remote(`/session/${session}/abort`,'POST',undefined,headers).catch(e=>setError(e.message))}><Square size={16}/></button>:<button className="send" title="发送" disabled={!connected||!prompt.trim()||submitting||!active?.enabled} onClick={send}><ArrowUp size={22}/></button>}</div></div><p className="composer-note">工具在远端执行 · 请核对重要结果 · Shift + Enter 换行</p></div>
 {files&&<div className="drawer"><div className="section-heading"><h3>会话文件</h3><button className="icon" title="刷新文件" aria-label="刷新文件" disabled={filesLoading} onClick={()=>browse(filePath)}><RefreshCw size={18}/></button><button className="icon" onClick={()=>{fileView.current=null;fileRequest.current++;setFiles(null);setFilesLoading(false)}}><X/></button></div><p className="muted">/workspace/sessions/{session}{filePath==='.'?'/':'/'+filePath}</p>{filesLoading&&<p role="status">正在刷新文件…</p>}{!filesLoading&&!files.length&&<p className="muted">当前目录暂无文件</p>}<button onClick={()=>browse('.')}>回到根目录</button>{files.map((f,i)=><button className="file-row" key={i} onClick={()=>f.type==='directory'||f.is_dir?browse((filePath==='.'?'':filePath+'/')+f.name):download('/cloud/files/download?'+new URLSearchParams({agent_id:agent,username:user,session_id:session,path:(filePath==='.'?'':filePath+'/')+f.name}),f.name).catch(e=>setError(e.message))}><FolderOpen size={16}/>{f.name}<span>{f.type==='file'?`${f.size} B`:''}</span></button>)}</div>}
 </section></div>
}
function Question({item,onAnswer}:{item:Dict,onAnswer:(v:string[][])=>void}){const[answers,setAnswers]=useState<string[][]>((item.questions||[]).map(()=>[]));return <div>{(item.questions||[]).map((q:Dict,i:number)=><label className="field" key={i}>{q.question}<select multiple={q.multiple} value={q.multiple?answers[i]:answers[i]?.[0]||''} onChange={e=>setAnswers(old=>old.map((a,j)=>i===j?Array.from(e.target.selectedOptions).map(x=>x.value):a))}><option value="">请选择</option>{(q.options||[]).map((o:Dict)=><option key={o.label} value={o.label}>{o.label} — {o.description}</option>)}</select><input placeholder="或输入回答" onChange={e=>setAnswers(old=>old.map((a,j)=>i===j?[e.target.value]:a))}/></label>)}<button onClick={()=>onAnswer(answers)}>提交回答</button></div>}
