import {useEffect,useState} from 'react';
import {Dict,remote} from './api';

export function RecoverySettings(){
 const[agents,setAgents]=useState<string[]>([]),[backoff,setBackoff]=useState('30,60,120');
 const[policy,setPolicy]=useState<Dict|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;remote('/cloud/admin/recovery-policy').then(value=>{if(active && Array.isArray(value.backoff_seconds)){setPolicy(value);setBackoff(value.backoff_seconds.join(','))}}).catch(e=>{if(active)setMessage(e.message)});remote('/cloud/agents').then(v=>{if(active&&Array.isArray(v))setAgents(v.map((a:Dict)=>a.id))}).catch(()=>{});return()=>{active=false}},[]);
 return <details className="panel"><summary>异常沙箱自动恢复设置</summary><p className="muted">只恢复能够确认空闲的异常沙箱。任务忙碌或未知、人工停止、Agent 归档及依赖服务异常时跳过。与配置发布共享操作队列，不会自动重发聊天。</p>{message&&<p role="status">{message}</p>}{policy&&<form onSubmit={async e=>{e.preventDefault();try{setPolicy(await remote('/cloud/admin/recovery-policy','PUT',{...policy,backoff_seconds:backoff.split(',').map(Number)}));setMessage('恢复策略已保存')}catch(e:any){setMessage(e.message)}}}><label className="checkbox"><input type="checkbox" checked={policy.enabled} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/>启用自动恢复</label>{[['failure_threshold','异常观察次数',1,20],['max_attempts','时间窗口内最多恢复次数',1,10],['window_seconds','重试窗口（秒）',60,86400],['stable_seconds','健康稳定后重置计数（秒）',30,3600]].map(([key,label,min,max])=><label key={String(key)}>{label}<input type="number" required min={Number(min)} max={Number(max)} value={policy[key]} onChange={e=>setPolicy({...policy,[key]:Number(e.target.value)})}/></label>)}<label>退避间隔（秒，逗号分隔）<input required value={backoff} onChange={e=>setBackoff(e.target.value)}/></label>{agents.map(id=><label className="checkbox" key={id}><input type="checkbox" checked={policy.agent_enabled?.[id]!==false} onChange={e=>setPolicy({...policy,agent_enabled:{...policy.agent_enabled,[id]:e.target.checked}})}/>{id}</label>)}<button className="primary">保存策略</button></form>}</details>;
}
